spring:
  jpa:

    database: postgresql
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/mydb
#    username: postgres
#    password: toor
#    driverClassName: org.postgresql.Driver

datasource:
  url: jdbc:postgresql://localhost:5432/mydb
  username: postgres
  password: toor
  driver-class-name: org.postgresql.Driver
